"""修訂版基本盒職業／次要。正式遊戲用 deal='base' 發這副；測試預設仍用玩具卡。"""

from oyster_omelette.cards import minor, occupation

BASE_CARDS = (
    minor("A002", "游耕", traveling=True, cost=(("food", 2),)),
    minor("A005", "黏土堆", traveling=True, cost=(("food", 1),)),
    minor("A009", "幼畜市", traveling=True, cost=(("sheep", 1),)),
    minor("A012", "飲水槽", cost=(("clay", 1),)),
    minor("A016", "夯土"),
    minor("A019", "手推犁", cost=(("wood", 1),)),
    minor("A024", "脫穀板", cost=(("wood", 1),), vp=1, prereq="2 Occupations"),
    minor("A026", "睡角", cost=(("wood", 1),), vp=1, prereq="2 Grain Fields"),
    minor("A032", "飼料槽", cost=(("wood", 2),)),
    minor("A033", "廣土", prereq="All Farmyard Spaces Used"),
    minor("A038", "羊毛毯", prereq="5 Sheep"),
    minor("A044", "池邊小屋", cost=(("wood", 1),), vp=1, prereq="Exactly 2 Occupations"),
    minor("A050", "牛奶罐", cost=(("clay", 1),)),
    minor("A053", "陶管", cost=(("clay", 1),)),
    minor("A055", "雜物間", cost=(("wood", 1), ("clay", 1))),
    minor("A056", "籃子", cost=(("reed", 1),)),
    minor("A063", "荷蘭風車", cost=(("wood", 2), ("stone", 2)), vp=2),
    minor("A067", "穀鏟", cost=(("wood", 1),)),
    minor("A069", "大溫室", cost=(("wood", 2),), prereq="2 Occupations"),
    minor("A071", "清田鏟", cost=(("wood", 1),)),
    minor("A075", "鋸木水車", cost=(("stone", 2),), vp=2, prereq="At Most 3 Occupations"),
    minor("A078", "獨木舟", cost=(("wood", 2),), vp=1, prereq="1 Occupation"),
    minor("A080", "石鉗", cost=(("wood", 1),)),
    minor("A083", "牧羊杖", cost=(("wood", 1),)),
    occupation("A086", "馴獸師"),
    occupation("A087", "修繕工"),
    occupation("A088", "樹籬看守"),
    occupation("A090", "扶犁人"),
    occupation("A092", "養父母"),
    occupation("A098", "畜舍建築師"),
    occupation("A102", "雜貨商"),
    occupation("A108", "採菇人"),
    occupation("A110", "抹灰工"),
    occupation("A111", "砌牆人"),
    occupation("A112", "鐮刀工"),
    occupation("A114", "季節工人"),
    occupation("A116", "伐木工"),
    occupation("A119", "拾薪人"),
    occupation("A120", "黏土屋匠"),
    occupation("A123", "屋架工"),
    occupation("A125", "聖職者"),
    occupation("A133", "吹牛者", players="3+"),
    occupation("A138", "魚叉手", players="3+"),
    occupation("A143", "石匠", players="3+"),
    occupation("A147", "牲口販", players="3+"),
    occupation("A155", "魔術師", players="4+"),
    occupation("A160", "魯特琴師", players="4+"),
    occupation("A165", "養豬人", players="4+"),
    minor("B002", "迷你牧場", traveling=True, cost=(("food", 2),)),
    minor("B008", "攤位", traveling=True, cost=(("grain", 1),)),
    minor("B010", "篷車", cost=(("wood", 3), ("food", 3))),
    minor("B013", "木匠廂房", cost=(("wood", 1), ("stone", 1))),
    minor("B016", "開礦鎚", cost=(("wood", 1),)),
    minor("B019", "鏵式犁", cost=(("wood", 2),), prereq="1 Occupation"),
    minor("B024", "套索", cost=(("reed", 1),)),
    minor("B025", "麵包鏟", cost=(("wood", 1),)),
    minor("B033", "壁爐架", cost=(("stone", 1),), vp=-3, prereq="Clay or Stone House"),
    minor("B036", "玻璃瓶", vp=4),
    minor("B039", "織布機", cost=(("wood", 1),), vp=1, prereq="2 Occupations"),
    minor("B045", "草莓畦", cost=(("wood", 1),), vp=2, prereq="2 Vegetable Fields"),
    minor("B047", "鯡魚鍋", cost=(("clay", 1),)),
    minor("B050", "攪乳器", cost=(("wood", 1),), vp=1, prereq="At Most 3 Occupations"),
    minor("B056", "小溪", prereq="Person on Fishing"),
    minor("B057", "洗碗間", cost=(("wood", 1), ("clay", 1))),
    minor("B061", "三圃輪作", prereq="3 Occupations"),
    minor("B062", "乾草叉", cost=(("wood", 1),)),
    minor("B066", "穀袋車", cost=(("wood", 2),), prereq="2 Occupations"),
    minor("B068", "豆田", cost=(("food", 1),), vp=1, prereq="2 Occupations"),
    minor("B074", "密林", prereq="5 Clay in Supply"),
    minor("B077", "黏土窪", cost=(("food", 1),), vp=1, prereq="3 Occupations"),
    minor("B080", "硬瓷", cost=(("clay", 1),)),
    minor("B084", "橡實籃", cost=(("reed", 1),), prereq="3 Occupations"),
    occupation("B087", "僱農"),
    occupation("B089", "馬夫"),
    occupation("B091", "耕地助手"),
    occupation("B095", "砌磚師傅"),
    occupation("B097", "學者"),
    occupation("B098", "有機農夫"),
    occupation("B099", "家庭教師"),
    occupation("B102", "顧問"),
    occupation("B104", "夢羊人"),
    occupation("B107", "僕役"),
    occupation("B108", "燒爐童"),
    occupation("B109", "造紙人"),
    occupation("B114", "無子女"),
    occupation("B118", "小農"),
    occupation("B121", "地質學家"),
    occupation("B123", "壓頂人"),
    occupation("B126", "木匠"),
    occupation("B136", "管家", players="3+"),
    occupation("B142", "菜販", players="3+"),
    occupation("B145", "柴薪工", players="3+"),
    occupation("B156", "倉管", players="4+"),
    occupation("B163", "牧師", players="4+"),
    occupation("B164", "羊語者", players="4+"),
    occupation("B166", "餵牛人", players="4+"),
)
